server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
security:
  user:
    name: user1
    password: test1
      
logging:
  level:
    org.springframework.security: DEBUG